In [64]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [65]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [66]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [67]:
df.shape

(891, 5)

In [68]:
df.dropna(inplace=True)

In [69]:
X=df.iloc[:,0:4]
y = df.iloc[:,-1]
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [70]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=10))

np.float64(0.6921165884194054)

## Feature Construction

In [71]:
X['Family Size'] = X['Pclass'] + X['SibSp'] + 1

In [72]:
X.head()

    Age  Pclass  SibSp  Parch  Family Size
0  22.0       3      1      0            5
1  38.0       1      1      0            3
2  26.0       3      0      0            4
3  35.0       1      1      0            3
4  35.0       3      0      0            4

In [73]:
def func(num):
    if num == 0:
        print("Are u dumb")
    elif num == 1:
        print("Alone")
    elif 2<=num<=5:
        print("Small")
    else:
        print("Large")

In [74]:
func(0)

Are u dumb

In [75]:
X['Family Type'] = X['Family Size'].apply(func)

Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Large
Small
Small
Large
Large
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Large
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Large
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Large
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small
Small

In [76]:
X.head()

    Age  Pclass  SibSp  Parch  Family Size Family Type
0  22.0       3      1      0            5        None
1  38.0       1      1      0            3        None
2  26.0       3      0      0            4        None
3  35.0       1      1      0            3        None
4  35.0       3      0      0            4        None

In [77]:
X.drop(columns=['Pclass','SibSp','Parch','Family Size'],inplace=True)

In [78]:
X.head()

    Age Family Type
0  22.0        None
1  38.0        None
2  26.0        None
3  35.0        None
4  35.0        None